version: "{build}-{branch}"
image: Visual Studio 2019
build: off
deploy: off
clone_folder: '%SCOOP_HOME%\alfa'
environment:
  SCOOP: C:\SCOOP
  SCOOP_HOME: C:\SCOOP\apps\scoop\current
  SCOOP_HELPERS: C:\projects\helpers
  lessmsi: '%SCOOP_HELPERS%\lessmsi\lessmsi.exe'
  innounp: '%SCOOP_HELPERS%\innounp\innounp.exe'
  matrix:
    - PowerShell: 5
    - PowerShell: 7
cache:
  - '%USERPROFILE%\Documents\WindowsPowerShell\Modules -> appveyor.yml, test\bin\*.ps1'
  - C:\projects\helpers  -> appveyor.yml, test\bin\*.ps1
matrix:
  fast_finish: true
for:
  - matrix:
      only:
        - PowerShell: 5
    install:
      - ps: . "$env:SCOOP_HOME\test\bin\init.ps1"
    test_script:
      - ps: . "$env:SCOOP_HOME\test\bin\test.ps1"
  - matrix:
      only:
        - PowerShell: 7
    install:
      - pwsh: . "$env:SCOOP_HOME\test\bin\init.ps1"
    test_script:
      - pwsh: . "$env:SCOOP_HOME\test\bin\test.ps1"
